export const headers = [
  { label: 'Month', key: 'month', dep: 'all' },
  { label: 'Signal', key: 'signalAcc', dep: 'Acc' },
  { label: 'Signal Cus', key: 'signalCus', dep: 'Cus' },
  { label: 'Signal Sale', key: 'signalSale', dep: 'Sale' },
  { label: 'Signal Ops', key: 'signalOps', dep: 'Ops' },
  { label: 'Signal Docs', key: 'signalDocs', dep: 'Docs' },
  { label: 'Signal Ops Docs', key: 'signalOpsDocs', dep: 'OpsDocs' },
  { label: 'BK. No', key: 'bkNo', dep: 'all' },
  { label: 'File Type', key: 'bookingType', dep: 'all' },
  { label: 'File.No', key: 'fileNo', dep: 'all' },
  { label: 'MST', key: 'mst', dep: 'all' },
  { label: 'Customer', key: 'customerName', dep: 'all' },
  { label: 'Shipper', key: 'shipper', dep: 'Cus' },
  { label: 'Consignee', key: 'consignee', dep: 'Cus' },
  { label: 'Agent', key: 'agent', dep: 'Cus' },
  { label: 'Term', key: 'term', dep: 'Sale' },
  { label: 'Service', key: 'service', dep: 'Sale' },
  { label: 'Transport', key: 'transport', dep: 'Sale' },
  { label: 'Cbm', key: 'cbm', dep: 'Cus' },
  { label: 'TEU', key: 'teu', dep: 'Cus' },
  { label: 'Type', key: 'type', dep: 'Cus' },
  { label: 'Type Quantity', key: 'typeQuantity', dep: 'Cus' },
  { label: 'VESSEL', key: 'vessel', dep: 'Cus' },
  { label: 'VESSEL TRANSIT', key: 'vesselTransit', dep: 'Cus' },
  { label: 'Shipping/Airline', key: 'shippingAirline', dep: 'Cus' },
  { label: 'Loading Date', key: 'loadingDate', dep: 'Cus' },
  { label: 'CLS', key: 'cls', dep: 'Cus' },
  { label: 'ETD', key: 'etd', dep: 'Cus' },
  { label: 'ETA', key: 'eta', dep: 'Cus' },
  { label: 'POR', key: 'por', dep: 'Cus' },
  { label: 'POL', key: 'pol', dep: 'Cus' },
  { label: 'POD', key: 'pod', dep: 'Cus' },
  { label: 'MBL No', key: 'mbl', dep: 'Cus' },
  { label: 'HBL No', key: 'hbl', dep: 'Cus' },
  { label: 'Cont & Sea No', key: 'containerNumber', dep: 'Cus' },
  { label: 'Depot', key: 'depot', dep: 'Cus' },
  { label: 'CFS', key: 'cfs', dep: 'Cus' },
  { label: 'MNF', key: 'mnf', dep: 'Docs' },
  { label: 'CF MNF', key: 'cfMnf', dep: 'Docs' },
  { label: 'Cược cont', key: 'cuocContDoc', dep: 'Docs' },
  { label: 'DO/EDO', key: 'doEdo', dep: 'Docs' },
  { label: 'Release Type', key: 'releaseType', dep: 'Docs' },
  { label: 'Release or Not', key: 'releaseOrNot', dep: 'Docs' },
  { label: 'Arival Actually', key: 'arrivalActually', dep: 'Cus' },
  { label: 'Door or Not', key: 'doorOrNot', dep: 'Sale' },
  { label: 'HR Sale', key: 'hrSale', dep: 'Sale' },
  { label: 'HR Cus', key: 'hrCus', dep: null },
  { label: 'HR Doc', key: 'hrDoc', dep: null },
  { label: 'HR Ops Doc', key: 'hrOpsDoc', dep: null },
  { label: 'HR Ops', key: 'hrOps', dep: null },
  { label: 'HR Acc', key: 'hrAcc', dep: null },
  { label: 'Chi cục', key: 'chicuc', dep: 'OpsDocs' },
  { label: 'Số tờ khai', key: 'sotokhai', dep: 'OpsDocs' },
  { label: 'Luồng', key: 'lane', dep: 'OpsDocs' },
  { label: 'Nhập/Xuất', key: 'nhapxuat', dep: 'OpsDocs' },
  { label: 'Ngày mở tờ khai', key: 'ngaymotokhai', dep: 'OpsDocs' },
  { label: 'Ngày thông quan', key: 'ngaythongquan', dep: 'OpsDocs' },
  { label: 'Soi chiếu', key: 'soiChieu', dep: 'Ops' },
  { label: 'Cược cont', key: 'cuocContOps', dep: 'Ops' },
  { label: 'Vận chuyển', key: 'vanchuyenOps', dep: 'Ops' },
  { label: 'Tiền cược', key: 'tienCuocOps', dep: 'Ops' },
  { label: 'Ngày cược', key: 'ngayCuocOps', dep: 'Ops' },
  { label: 'Ngày hoàn', key: 'ngayHoanAcc', dep: 'Acc' },
  { label: 'Cbm', key: 'cbmDocOps', dep: 'OpsDocs' },
  { label: 'TEU', key: 'teuDocOps', dep: 'OpsDocs' },
  { label: 'Type', key: 'typeDocOps', dep: 'OpsDocs' },
  { label: 'Type Quantity', key: 'typeQuantityDocOps', dep: 'OpsDocs' },
  { label: 'Số cont/ Chì', key: 'containerNumberDocOps', dep: 'OpsDocs' },
  { label: 'Depot/CFS', key: 'depotCfsDocOps', dep: 'OpsDocs' },
  { label: 'Nhà xe', key: 'carrierOps', dep: 'Ops' },
  { label: 'Ngày trả', key: 'returnDateSale', dep: 'Sale' },
  { label: 'Địa chỉ trả hàng', key: 'deliveryAddressSale', dep: 'Sale' },
  { label: 'Người nhận', key: 'recipientSale', dep: 'Sale' },
  { label: 'Số điện thoại', key: 'picPhoneSale', dep: 'Sale' },
  { label: 'Xác nhận trả hàng(ngày)', key: 'confirmationReturnDateSale', dep: 'Sale' },
  { label: 'Income', key: 'incomeSale', dep: 'Sale' },
  { label: 'VAT(income)', key: 'vatIncomeSale', dep: 'Sale' },
  { label: 'Cost', key: 'costMix', dep: 'Mix' },
  { label: 'VAT cost', key: 'vatCostMix', dep: 'Mix' },
  { label: 'Profit', key: 'profitMix', dep: 'Mix' },
  { label: 'Commission Client', key: 'commissionClientMix', dep: 'Mix' },
  { label: 'ROE %', key: 'roeMix', dep: 'Mix' },
  { label: 'Ngày gửi debit', key: 'ngayGuiDebitAcc', dep: 'Acc' },
  { label: 'Hạn thanh toán', key: 'hanThanhToanAcc', dep: 'Acc' },
  { label: 'Ngày thanh toán', key: 'ngayThanhToanAcc', dep: 'Acc' },
  // { label: 'PIC name', key: 'picName' },
  // { label: 'PIC phone', key: 'picPhone' },
  // { label: 'PIC email', key: 'picEmail' },
  { label: 'Ngày tạo', key: 'timestamp', dep: 'all' },
  { label: 'Ghi chú', key: 'note', dep: 'all' },
]

export const bookingObject = {
  month: null,
  signalAcc: null,
  signalCus: null,
  signalSale: null,
  signalOps: null,
  signalDocs: null,
  signalOpsDocs: null,
  bkNo: null,
  bookingType: null,
  fileNo: null,
  mst: null,
  customerName: null,
  shipper: null,
  consignee: null,
  agent: null,
  term: null,
  service: null,
  transport: null,
  cbm: null,
  teu: null,
  type: null,
  typeQuantity: null,
  vessel: null,
  vesselTransit: null,
  shippingAirline: null,
  loadingDate: null,
  cls: null,
  etd: null,
  eta: null,
  por: null,
  pol: null,
  pod: null,
  mbl: null,
  hbl: null,
  containerNumber: null,
  depot: null,
  cfs: null,
  mnf: false,
  cfMnf: false,
  cuocContDoc: false,
  doEdo: null,
  releaseType: null,
  releaseOrNot: false,
  arrivalActually: null,
  doorOrNot: false,
  hrSale: null,
  hrCus: null,
  hrDoc: null,
  hrOpsDoc: null,
  hrOps: null,
  hrAcc: null,
  chicuc: null,
  sotokhai: null,
  lane: null,
  nhapxuat: null,
  ngaymotokhai: null,
  ngaythongquan: null,
  soiChieu: false,
  cuocContOps: false,
  vanchuyenOps: false,
  tienCuocOps: null,
  ngayCuocOps: null,
  ngayHoanAcc: null,
  tongTienOps: null,
  cbmDocOps: null,
  teuDocOps: null,
  typeDocOps: null,
  typeQuantityDocOps: null,
  containerNumberDocOps: null,
  depotCfsDocOps: null,
  carrierOps: null,
  returnDateSale: null,
  deliveryAddressSale: null,
  recipientSale: null,
  picPhoneSale: null,
  confirmationReturnDateSale: null,
  incomeSale: null,
  vatIncomeSale: null,
  costMix: null,
  vatCostMix: null,
  profitMix: null,
  commissionClientMix: null,
  roeMix: null,
  ngayGuiDebitAcc: null,
  hanThanhToanAcc: null,
  ngayThanhToanAcc: null,
  picName: null,
  picPhone: null,
  picEmail: null,
  timestamp: null,
  note: null,
}

export const depColor = {
  sale: 'bg-green-100 border-green-500',
  cus: 'bg-blue-100 border-blue-500',
  doc: 'bg-blue-200 border-blue-500',
  acc: 'bg-yellow-100 border-yellow-500',
  ops: 'bg-orange-100 border-orange-500',
  mix: 'bg-purple-100 border-purple-500',
}

export const generalFields = ['mst', 'customerName', 'bkNo', 'fileNo', 'timestamp', 'note']

export const saleFields = [
  'term',
  'doorOrNot',
  'returnDateSale',
  'deliveryAddressSale',
  'recipientSale',
  'picPhoneSale',
  'incomeSale',
  'vatIncomeSale',
  'service',
  'transport',
]

export const cusFields = [
  'signalCus',
  'shipper',
  'consignee',
  'agent',
  'cbm',
  'teu',
  'type',
  'typeQuantity',
  'vessel',
  'vesselTransit',
  'shippingAirline',
  'loadingDate',
  'cls',
  'etd',
  'eta',
  'por',
  'pol',
  'pod',
  'mbl',
  'hbl',
  'containerNumber',
  'depot',
  'cfs',
  'arrivalActually',
]

export const docFields = [
  'mnf',
  'cfMnf',
  'cuocContDoc',
  'doEdo',
  'releaseType',
  'confirmationReturnDateSale',
  'releaseOrNot',
]

export const opsFields = [
  'soiChieu',
  'cuocContOps',
  'vanchuyenOps',
  'tienCuocOps',
  'ngayCuocOps',
  'carrierOps',
]

export const accFields = [
  'ngayHoanAcc',
  'ngayGuiDebitAcc',
  'hanThanhToanAcc',
  'ngayThanhToanAcc',
  'signalAcc',
]

export const opsDocFields = [
  'chicuc',
  'sotokhai',
  'lane',
  'nhapxuat',
  'ngaymotokhai',
  'ngaythongquan',
  'cbmDocOps',
  'teuDocOps',
  'typeDocOps',
  'typeQuantityDocOps',
  'containerNumberDocOps',
  'depotCfsDocOps',
]

export const checkboxFields = [
  'doorOrNot',
  'releaseOrNot',
  'mnf',
  'cfMnf',
  'cuocContDoc',
  'soiChieu',
  'cuocContOps',
  'vanchuyenOps',
]

export const agents = [
  { value: null, label: 'None' },
  { value: 'IQ CARGO', label: 'IQ CARGO' },
  { value: 'EGLOBE', label: 'EGLOBE' },
  { value: 'ANB', label: 'ANB' },
  { value: 'OMEGA', label: 'OMEGA' },
  { value: 'PCF24', label: 'PCF24' },
  { value: 'QUANTERM', label: 'QUANTERM' },
  { value: 'EMC', label: 'EMC' },
]
