export const customerHeaders = [
  {
    label: 'Mã người nhập khẩu',
    key: 'mst',
  },
  {
    label: 'Tên người nhập khẩu',
    key: 'buyerName',
  },
  {
    label: 'Địa chỉ người nhập khẩu',
    key: 'buyerAddress',
  },
  {
    label: 'Số điện thoại người nhập khẩu',
    key: 'buyerMobile',
  },
  {
    label: 'Mã người uỷ thác nhập khẩu',
    key: 'buyerRefCode',
  },
  {
    label: 'Tên người uỷ thác nhập khẩu',
    key: 'buyerRefName',
  },
  {
    label: 'Mã người xuất khẩu',
    key: 'sellerRefCode',
  },
  {
    label: 'Tên người xuất khẩu',
    key: 'sellerName',
  },
  {
    label: 'Mã bưu chính',
    key: 'postalCode',
  },
  {
    label: 'Mã điều kiện giá hoá đơn',
    key: 'invoicePriceCondition',
  },
  {
    label: 'Mã số hàng hoá',
    key: 'goodsCode',
  },
  {
    label: 'Mô tả hàng hoá',
    key: 'goodsDescription',
  },
  {
    label: 'Mã nước xuất xứ',
    key: 'originCountryCode',
  },
  {
    label: 'Tên nước xuất xứ',
    key: 'originCountryName',
  },
]

export const customerPool = [
  {
    mst: 201753194,
    buyerName: 'CôNG TY TNHH PHáT TRIểN THươNG MạI Và XUấT NHậP KHẩU TRườNG GIANG',
    buyerAddress:
      'Tổ dân phố số 2( nhà bà Vũ Thị Yến), Phường Đằng Hải, Quận Hải An, Thành phố Hải Phòng, Việt Nam',
    buyerMobile: '0978362053',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'ZHEJIANG TIANCHANG PLASTIC FABRIC CO., LTD.',
    postalCode: 86,
    invoicePriceCondition: 'FOB',
    goodsCode: 39219090,
    goodsDescription:
      'Màng PVC có cốt ở giữa bằng sợi Polyester loại không xốp, đã gia cố, chưa in hình, chữ, dùng để in ấn, quảng cáo. Rộng x dài: 2.7 x 50m, Hàng mới 100% ( NSX: ZHEJIANG TIANCHANG PLASTIC)',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 600387327,
    buyerName: 'Công Ty Cổ Phần Tce Vina Denim',
    buyerAddress: 'LÔ S6+S7, KHU CÔNG NGHIỆP HÒA XÁ, XÃ MỸ XÁ, TP NAM ĐỊNH',
    buyerMobile: '02283677025',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'PICANOL NV',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 84463000,
    goodsDescription:
      'Máy dệt kiếm hiệu Picanol model OPTIMAX-I-4-R 220,khổ dệt tối đa 2.2m, mới 100%, hoạt động bằng điện(gồm 6 đầu máy ) Nhập khẩu theo DM số 04-DM-HQNĐ ngày 26/05/2017.',
    originCountryCode: 'BE',
    originCountryName: 'BELGIUM',
  },
  {
    mst: 102143568,
    buyerName: 'Công Ty Cổ Phần Tp Hoàng Kim',
    buyerAddress: 'Số 162, tổ 66, phường Tương Mai, quận Hoàng Mai, HN',
    buyerMobile: '0433766077',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'TS GLOBAL METAL CO.,',
    postalCode: 64064,
    invoicePriceCondition: 'FOB',
    goodsCode: 76012000,
    goodsDescription:
      'Phôi nhôm hợp kim chưa gia công nguyên liệu sản xuất nhôm định hình, loại 6063 (Al=98%) đường kính 4.0 inch (102mm+/-1) dài 5800 mm, hàng mới 100%',
    originCountryCode: 'TW',
    originCountryName: 'TAIWAN',
  },
  {
    mst: 102304744,
    buyerName: 'Công Ty TNHH Một Thành Viên Thương Mại Và Dịch Vụ Bách Linh',
    buyerAddress: 'Số 33 Phố Thợ Nhuộm, Phường Cửa Nam, Quận Hoàn Kiếm, Hà Nội',
    buyerMobile: '0978689999',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'QIAQIA FOOD CO.,LTD',
    postalCode: '( +86 )',
    invoicePriceCondition: 'FOB',
    goodsCode: 20081990,
    goodsDescription:
      'Hạt hướng dương đã chế biến ROASTED SUNFLOWER SEEDS ( CHACHEER )( mixed flavor) 130g x 64gói/ thùng, mới 100%( tên khoa học : Helianthus annus L )',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 2500288968,
    buyerName: 'Công ty TNHH PIAGGIO Việt Nam',
    buyerAddress: 'Lô M, KCN Bình Xuyên, Thị trấn Hương Canh, Huyện Bình Xuyên, Vĩnh Phúc',
    buyerMobile: '0211.3593666',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'CHONGQING ZONGSHEN ENGINE MANUFACTURE CO., LTD',
    postalCode: '(+86)',
    invoicePriceCondition: 'FOB',
    goodsCode: 84073100,
    goodsDescription:
      'CM267004#&P/N: CM267004 - Động cơ xe Liberty I-GET 50cc 4S/3V, hàng mới 100% linh kiện lắp ráp xe máy Piaggio',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 313900369,
    buyerName: 'Công Ty TNHH Passio Tuning',
    buyerAddress: 'Số 12 đường Quốc Hương, Phường Thảo Điền, Quận 2, TP Hồ Chí Minh',
    buyerMobile: '090 2666845',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: "ADVANCED POWER SYSTEMS INT'L INC.",
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 38159000,
    goodsDescription:
      'Bộ chất xúc tác xử lý nhiên liệu - FITCH FUEL CATALYST F5TS-1, Thành phần chất xúc tác : TIN , BISMUTH, ZINC, ANTIMONY, SILVER , Trọng lượng 1 bộ = 0.09 kg.Hàng mới 100%',
    originCountryCode: 'US',
    originCountryName: 'U.S.A.',
  },
  {
    mst: 106328665,
    buyerName: 'Công ty TNHH Omron Việt Nam',
    buyerAddress: 'Tầng 9, Mipec tower, 229 Tây Sơn, P.Ngã Tư Sở, Q.Đống Đa, TP.Hà Nội.',
    buyerMobile: '0462770288',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'OMRON ELECTRONIC COMPONENTS PTE LTD',
    postalCode: '(+65)',
    invoicePriceCondition: 'FOB',
    goodsCode: 85365059,
    goodsDescription:
      'Công tắc điện cơ bật nhanh dùng cho đèn phanh xe máy có điện áp 12V, <= 4.5A C8EA-CR221 (C8EA0015R), hãng sản xuất Omron, mới 100%',
    originCountryCode: 'ID',
    originCountryName: 'INDNSIA',
  },
  {
    mst: 100933433,
    buyerName: 'Doanh Nghiệp tư nhân Sơn Hoàng',
    buyerAddress: 'Số 1 Bích Câu- Phường Quốc Tử Giám- Quận Đống Đa- Hà Nội',
    buyerMobile: '12345678',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'CHEONIL CO., LTD',
    postalCode: '(+82)28',
    invoicePriceCondition: 'FOB',
    goodsCode: 73241010,
    goodsDescription:
      'Chậu rửa bát  Inox loại 02 hộc. Mã ISD870( 870x 480 x 180) mm.Kèm xiphông xả. Hiệu CICO, Mới 100%',
    originCountryCode: 'KR',
    originCountryName: 'R.KOREA',
  },
  {
    mst: 107065225,
    buyerName: 'Công Ty TNHH Xuất Nhập Khẩu Quốc Tế Viêm Hoàng',
    buyerAddress:
      'Số 21, tổ dân phố Tháp, phường Đại Mỗ, Quận Nam Từ Liêm, Thành phố Hà Nội, Việt Nam.',
    buyerMobile: '0463271687',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'LIANSU GROUP COMPANY LIMITED',
    postalCode: 852,
    invoicePriceCondition: 'FOB',
    goodsCode: 39172300,
    goodsDescription: 'ống nhựa PVC hiệu Lesso đã nong đầu dài 5,8m/cái, phi 110mm, hàng mới 100%',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 102655453,
    buyerName: 'Công ty TNHH Honda Trading Việt Nam',
    buyerAddress:
      'Tầng 8, toà nhà Mặt Trời Sông Hồng, số 23 Phan Chu Trinh, P. Phan Chu Trinh, Q. Hoàn Kiếm, Hà Nội',
    buyerMobile: '0439334591',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'HONDA TRADING CORPORATION - JAPAN',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 85122091,
    goodsDescription:
      'Cụm đèn sau LIGHT ASSY REAR COMB 33700-K44-V022-M1.Phụ tùng dùng cho xe máy Honda. Hàng mới 100%',
    originCountryCode: 'ID',
    originCountryName: 'INDNSIA',
  },
  {
    mst: 700643278,
    buyerName: 'Công ty TNHH ANAM ELECTRONICS Việt Nam',
    buyerAddress:
      'Khu Công Nghiệp Đồng Văn II, Xã Bạch Thượng, Huyện Duy Tiên, Tỉnh Hà Nam, Việt Nam',
    buyerMobile: '035 13582255',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'ANAM ELECTRONICS H.K. LIMITED',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 85043249,
    goodsDescription: 'AV-CLTTRA#&Biến áp nguồn',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 102653752,
    buyerName: 'Công Ty TNHH Công Nghệ Phát Triển Thiên Niên Kỷ',
    buyerAddress: 'Số 454 đường Lạc Long Quân, P.Nhật Tân, Q.Tây Hồ, Hà Nội',
    buyerMobile: '0437558038',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'COELME S.P.A',
    postalCode: 39,
    invoicePriceCondition: 'FOB',
    goodsCode: 85353020,
    goodsDescription:
      'Cầu dao cách ly 123kV, 3pha, dòng điện 1250A, 31.5kA/3s, loại CBD-EE 123-1250, 1xCD212+1xCD101, 2 lưỡi tiếp địa, hàng mới 100%, hiệu Coelme',
    originCountryCode: 'IT',
    originCountryName: 'ITALY',
  },
  {
    mst: 3600659583,
    buyerName: 'Công Ty TNHH Đông Phương Đồng Nai  Việt Nam',
    buyerAddress: 'Bắc Sơn-Trảng Bom-Đồng Nai',
    buyerMobile: '0613968790',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'FENGTAY ENTERPRISES CO.,LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 56039400,
    goodsDescription: 'Sản phẩm không dệt 61" - Flyweave jqd wvn (54 yard = 76.51 m2)',
    originCountryCode: 'KR',
    originCountryName: 'R.KOREA',
  },
  {
    mst: 100774342,
    buyerName: 'Công Ty TNHH Yamaha Motor Việt Nam',
    buyerAddress: 'Xã Trung Giã, Huyện Sóc Sơn, Hà Nội',
    buyerMobile: '84.4.8217457',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'THAI YAMAHA MOTOR  CO., LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 83012000,
    goodsDescription:
      'Chìa khóa thông minh /B74-H6261-01, linh kiện dùng cho xe máy Yamaha mới 100%',
    originCountryCode: 'TH',
    originCountryName: 'THAILND',
  },
  {
    mst: 102747337,
    buyerName: 'Công ty TNHH 1TV sản xuất kinh doanh xuất nhập khẩu L.U.C.K.Y.S.T.A.R',
    buyerAddress:
      'Số 74, ngõ 117, phố Trần Cung, phường Cổ Nhuế 1, quận Bắc Từ Liêm, thành phố Hà Nội.',
    buyerMobile: '0437858992',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'SINO KING INDUSTRIAL LIMITED',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 34039990,
    goodsDescription:
      'Mỡ bôi trơn, dạng đặc, dùng cho máy cơ khí NS-1-4 ( 400g/tuýp ). Hsx :LUBE. Hàng mới 100%.',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 105869735,
    buyerName: 'Công Ty TNHH Đầu Tư Thương Mại Và Xuất Nhập Khẩu Nhật Minh',
    buyerAddress: 'Số 7B, Vũ Trọng Phụng, p. Thanh Xuân Trung, Thanh Xuân, Hà Nội',
    buyerMobile: '0437823498',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'ZHONGSHAN ZHENGDE COMMERCIAL CO.,LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 84146019,
    goodsDescription:
      'Máy hút khử mùi hiệu SEVILLA model SV- 70 inox, 70 cm, bằng inox, hai động cơ, công suất 2*110W,hàng  mới 100%',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 307787891,
    buyerName: 'Công Ty TNHH Adidas Việt Nam',
    buyerAddress: '2 Hai Trieu, Q1',
    buyerMobile: '39157000',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'DONGJU SPORT CO;LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 42029290,
    goodsDescription: 'A92283 - TÚI XÁCH - POLYESTER. MỚI 100%, HIỆU TMAG',
    originCountryCode: 'VN',
    originCountryName: 'VIETNAM',
  },
  {
    mst: 106695383,
    buyerName: 'Công Ty TNHH Thương Mại Thuận Bảo',
    buyerAddress:
      'Số 4, Ngõ 22, Phố Trung Kính, Phường Trung Hoà, Quận Cầu Giấy, Thành Phố Hà Nội, Việt Nam',
    buyerMobile: '0989699898',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'FUJIAN PROVINCE CHANGLE CITY HUAWEI KNITTING CO.,LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 58023030,
    goodsDescription:
      'Vải sợi dệt thoi có chần sợi nổi vòng (80% Polyester, 20% cotton), khổ 2m3, 149 cuộn/21080 mét.(chưa nhuộm & tráng phủ) Mới 100%, HSX: FUJIAN PROVINCE CHANGLE CITY HUAWEI KNITTING CO.,LTD.',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 201186139,
    buyerName: 'Công ty TNHH công nghệ máy văn phòng KYOCERA Việt Nam',
    buyerAddress: 'Lô đất 56A,56B,56C Khu đô thị,CN & DV VSIP HP',
    buyerMobile: '0313.8843982',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'KYOCERA DOCUMENT TECHNOLOGY COMPANY (HK) LTD.',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 84439990,
    goodsDescription:
      '3V2RV00050-0001#&Bộ phận hiện ảnh trong máy in P2100 DLP UNIT(CN)ASSY  (1 chiếc / 1 hộp carton x 4 chiếc / 1 thùng carton)3V2RV00050',
    originCountryCode: 'VN',
    originCountryName: 'VIETNAM',
  },
  {
    mst: 106860742,
    buyerName: 'Công ty TNHH Thương mại Quốc tế Hải Thịnh',
    buyerAddress: 'Số 26C, ngõ 18, Đội 2, Xã Tả Thanh Oai, Huyện Thanh Trì, TP Hà Nội, Việt Nam',
    buyerMobile: '0313853356',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'UNI SUPPLIES LIMITED',
    postalCode: '(+852)',
    invoicePriceCondition: 'FOB',
    goodsCode: 84423010,
    goodsDescription:
      'Máy chế bản CTP Ausetter T864, Số Serial máy: 610812694, dùng để chế bản in, khổ : 1130x920mm, tốc độ 28 bản/h, 240V/4KW, năm sx 2017, nhà sản xuất Guangzhou Amsky Technoligy Co.,Ltd, mới 100%',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 100774342,
    buyerName: 'Công Ty TNHH Yamaha Motor Việt Nam',
    buyerAddress: 'Xã Trung Giã, Huyện Sóc Sơn, Hà Nội',
    buyerMobile: '84.4.8217457',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'YAMAHA MOTOR ASIA PTE., LTD',
    postalCode: '(+65)',
    invoicePriceCondition: 'FOB',
    goodsCode: 84831024,
    goodsDescription: 'Trục cam  / 1FC-E2171-00 /dùng cho xe máy YAMAHA / hàng mới 100%',
    originCountryCode: 'ID',
    originCountryName: 'INDNSIA',
  },
  {
    mst: 101526991,
    buyerName: 'Công Ty Cổ Phần Bóng Đèn Phích Nước Rạng Đông',
    buyerAddress: '87-89 Phố Hạ đình, phường Thanh Xuân Trung, Quận Thanh Xuân, TP Hà nội',
    buyerMobile: '043.8584310 / 043.85',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'HY TECHNOLOGY DEVELOPMENT (H.K,) CO.,LIMITED',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 85411000,
    goodsDescription: 'Đi ốt mã RL207 dùng để sản xuất nguồn đèn LED  , hãng sx HY, hàng mới 100%',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 2500150543,
    buyerName: 'Công ty HONDA VIETNAM',
    buyerAddress: 'Phúc Thắng, Phúc Yên, Vĩnh Phúc',
    buyerMobile: '0431111111',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'ASIAN HONDA MOTOR CO.,LTD',
    postalCode: 10500,
    invoicePriceCondition: 'FOB',
    goodsCode: 40094290,
    goodsDescription:
      'Ống cao su dẫn khí bầu lọc xe CIVIC - 17225-R6A-J00 - PT XE Ô TÔ HONDA. Hàng mới 100%',
    originCountryCode: 'TH',
    originCountryName: 'THAILND',
  },
  {
    mst: 900637507,
    buyerName: 'Công Ty TNHH Fami',
    buyerAddress: 'xa Vinh Khuc, huyen Van Giang, tinh Hung Yen',
    buyerMobile: '0321 398 0820',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'EG TEC CO.',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 39204900,
    goodsDescription:
      'NVL để sản xuất đồ gỗ nội thất văn phòng: Nẹp nhựa cứng bằng PVC, rộng 32mm, dạng cuộn, màu xám (SG), hàm lượng chất dẻo dưới 6%, hàng mới 100%',
    originCountryCode: 'KR',
    originCountryName: 'R.KOREA',
  },
  {
    mst: 104994500,
    buyerName: 'Công ty TNHH điện tử lưỡng diện Việt Nam',
    buyerAddress: 'Lô A2, CN1, CCN Tập trung vừa và nhỏ Từ Liêm, Minh Khai, Từ Liêm, Hà Nội',
    buyerMobile: '04 37805224',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'DUAL POWER TRADING  CO., LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 39021090,
    goodsDescription: 'Hạt nhựa  Polymer Propylene PP(BI452), hàng mới 100 %',
    originCountryCode: 'KR',
    originCountryName: 'R.KOREA',
  },
  {
    mst: 105155018,
    buyerName: 'Công Ty Cổ Phần Dhs Việt Nam',
    buyerAddress: 'Thôn An Hạ, xã An Thượng, Huyện Hoài Đức, Thành phố Hà Nội, Việt Nam',
    buyerMobile: '0433656544',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'RAINBOW TIMBER LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 44039990,
    goodsDescription:
      'Gỗ  Azobe dạng lóng ( đường kính: 70cm&up, dài 7m&up ) gỗ không cấm nhập, không nằm trong danh mục Cites ( Tên KH: Lophira alata ), số khối thực 23,24 M3 = 6391 EUR',
    originCountryCode: 'GQ',
    originCountryName: 'EQ.GNEA',
  },
  {
    mst: 9999999999998,
    buyerName: 'Cá nhân - Tổ chức không có mã số thuế',
    buyerAddress: 'Số 10 Ông Ích Khiêm, Ba Đình, Hà Nội, ,',
    buyerMobile: '+84437833770',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'BORMIOLI ROCCO SPA',
    postalCode: 43036,
    invoicePriceCondition: 'FOB',
    goodsCode: 70109010,
    goodsDescription:
      'Hũ thủy tinh 415ml, màu hồng, đường kính 7.77*13.6cm, hiệu Bormioli, item 357753MQE121990. Mới 100%',
    originCountryCode: 'IT',
    originCountryName: 'ITALY',
  },
  {
    mst: 104498189,
    buyerName: 'Công ty TNHH AK Chemtech Hà Nội',
    buyerAddress: 'KCN YÊN PHONG, XÃ LONG CHÂU, HUYỆN YÊN PHONG, TỈNH BẮC NINH',
    buyerMobile: '(+84)43',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'AK CHEMTECH CO.,LTD.',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 32089090,
    goodsDescription:
      '1RC0188#&AMORSO 7830 (Dung dịch polyme gốc Xenlulo trong dung môi hữu cơ, hàm lượng dung môi >50%) )',
    originCountryCode: 'KR',
    originCountryName: 'R.KOREA',
  },
  {
    mst: 104908205,
    buyerName: 'Công Ty TNHH Thiết Bị & Phụ Tùng An Khánh',
    buyerAddress: 'Số 16, Ngõ 119/189 Nguyễn Ngọc Vũ, P. Trung Hòa, Q. Cầu Giấy,TP. Hà Nội',
    buyerMobile: '04.66759358',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'SANKYO REELS, INC.',
    postalCode: 81,
    invoicePriceCondition: 'FOB',
    goodsCode: 40094290,
    goodsDescription:
      'Cuộn dây tự rút bằng cao su dạng ống 6.5mm x 10m, không dẫn điện, dùng dẫn hơi, có đầu nối đi kèm, màu đỏ SHS-210Z hiệu Sankyo.Hàng mới 100 %',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 107001944,
    buyerName: 'Công Ty TNHH Sản Xuất Và Thương Mại Đầu Tư Đại Dương',
    buyerAddress: 'Số 15, ngõ 20/15 Hồ Tùng Mậu, Phường Mai Dịch, Quận Cầu Giấy, Hà Nội',
    buyerMobile: '0968836999',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'SHENZHEN BAO TU IMPORT AND EXPORT CO.,LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 85098090,
    goodsDescription:
      'Máy làm mát bằng hơi nước hiệu DAICHIPRO (Evaporative AirCoolers - Brand  DAICHIPRO), cs: 180W, 3 tốc độ, bình chứa nước:40L, model: DCP-5500 , NW:16.8kg/chiếc, hàng mới 100%',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 3700228661,
    buyerName: 'CôNG TY TRáCH NHIệM HữU HạN SCHNEIDER ELECTRIC VIệT NAM',
    buyerAddress: '364 Cộng Hòa, Quận Tân Bình, Tp Hồ Chí Minh',
    buyerMobile: '84.8.38103103',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'SCHNEIDER ELECTRIC INDUSTRIES SAS',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 85362013,
    goodsDescription:
      '(A9K24263)  Bộ ngắt mạch tự động 63A - ACTI9 IK60N 2P 63A C MINIATURE CIRCUIT B',
    originCountryCode: 'BG',
    originCountryName: 'BULGAR',
  },
  {
    mst: 201577005,
    buyerName: 'Công Ty Cổ Phần Thương Mại Kkh',
    buyerAddress: 'Số 224 Đông Khê, Phường Đằng Giang, Quận Ngô quyền, Hải phòng',
    buyerMobile: '0936590869',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'MAYFLOWER LOGISTICS NIG LTD',
    postalCode: 234708,
    invoicePriceCondition: 'FOB',
    goodsCode: 12119099,
    goodsDescription:
      'Hạt thảo quyết minh khô  ( Cassia obtusifolia), không dùng để làm thuốc. Hàng mới 100%. (hàng không nằm trong danh mục CITES)',
    originCountryCode: 'NG',
    originCountryName: 'NIGERIA',
  },
  {
    mst: 100113381,
    buyerName: 'Công Ty TNHH Lixil Việt Nam',
    buyerAddress: 'Dương Xá, Gia Lâm, Hà Nội',
    buyerMobile: '8766152',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'LIXIL CORP',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 32071000,
    goodsDescription: 'Bột màu hồng M-668 ((Zn,Fe)SiO4), 25kg/hộp  (dùng sản xuất sứ vệ sinh).',
    originCountryCode: 'JP',
    originCountryName: 'JAPAN',
  },
  {
    mst: 800352836,
    buyerName: 'Công ty TNHH AIDEN Việt Nam',
    buyerAddress:
      'Lô đất L5, Khu công nghiệp Nam Sách, Phường Ái Quốc, Thành phố Hải Dương, tỉnh Hải Dương, Việt Nam',
    buyerMobile: '02203 751 450',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'SHIN TECH ENGINEERING LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 85423900,
    goodsDescription: 'X0080#&Mạch tổ hợp',
    originCountryCode: 'PH',
    originCountryName: 'PHILPIN',
  },
  {
    mst: 101535883,
    buyerName: 'Công ty TNHH thiết bị giáo dục và đồ chơi Phương Anh',
    buyerAddress: 'Số 151 Phố Lê Duẩn, Phường Cửa Nam, Quận Hoàn Kiếm, TP. Hà Nội',
    buyerMobile: '6422816',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'KUNMING BINHUI BUSINESS TRADING CO., LTD.',
    postalCode: '86-871-65',
    invoicePriceCondition: 'FOB',
    goodsCode: 84807990,
    goodsDescription:
      'Khuôn đúc dùng để đúc ghế nhựa, chất liệu bằng sắt, kích thước (800 x 650 x 620)mm,  nhà sản xuất YangZhou YongZheng Rotational Equipment, hàng mới 100%',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 300792187,
    buyerName: 'Công Ty TNHH Panasonic AVC Việt Nam',
    buyerAddress: 'Lô 73-75. Đường D, KCX Sài Gòn-Linh Trung, P.Linh Trung, Q.Thủ Đức , TP.HCM',
    buyerMobile: '08 372 444 92',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'QUANTIGE INDUSTRY SDN BHD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 39269099,
    goodsDescription: 'miếng nhựa lắp ráp tivi LCD - TMK4VX010',
    originCountryCode: 'MY',
    originCountryName: 'MALYSIA',
  },
  {
    mst: 105273501,
    buyerName: 'Công Ty Cổ Phần Công Nghiệp M.E.C.I',
    buyerAddress:
      'Số 164, Đường Nguyễn Trãi, Phường Thượng Đình, Quận Thanh Xuân, Thành Phố Hà Nội, Việt Nam',
    buyerMobile: '0433216300',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'GUANGZHOU CHUANTONG IMP.&EXP.TRADING CO.,LTD',
    postalCode: '(+86)',
    invoicePriceCondition: 'FOB',
    goodsCode: 39204900,
    goodsDescription:
      'Màng nhựa PVC trong chống tĩnh điện, kích thước 1.0mmx1.37mx30m, hàng mới 100% (hàng chưa được gia cố hoặc kết hợp với các vật liệu khác, không xốp, không dính), nhà SX Hebei Jiurun Rubber Products Co',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 801031930,
    buyerName: 'Công ty TNHH máy Brother Việt Nam',
    buyerAddress: 'Lô CN 2-4 KCN Tân Trường Huyện Cẩm Giàng Tỉnh Hải Dương',
    buyerMobile: '0220 3545 889',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'ZHEJIANG FOUNDER MOTOR CORPORATION LTD.',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 84529099,
    goodsDescription: 'BMV009#&Biến áp',
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 100101403,
    buyerName: 'Tổng công ty Đức Giang - Công ty cổ phần',
    buyerAddress: '59 Đức Giang, Long Biên, Hà Nội',
    buyerMobile: '031.3766415',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'SHINHWA TEX CO.,LTD/SUZHOU RICH GRANG IMP.& EXP. CO.,LTD',
    postalCode: '(+82)',
    invoicePriceCondition: 'FOB',
    goodsCode: 59039000,
    goodsDescription:
      "290#&Vải chính dệt thoi 100% polyester (tráng phủ Milky) W55'' (130g/m2, 4997yds), hàng mới 100%",
    originCountryCode: 'CN',
    originCountryName: 'CHINA',
  },
  {
    mst: 201722189,
    buyerName: 'Công Ty TNHH Dong-A Hwasung Vina',
    buyerAddress: 'lô k4 KCN Tràng Duệ-xã Lê Lợi, huyện An Dương, thành phố Hải Phòng, Việt Nam',
    buyerMobile: '0312248698',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'DONG-A HWA SUNG CO .,LTD',
    postalCode: '( +82 )',
    invoicePriceCondition: 'FOB',
    goodsCode: 38123000,
    goodsDescription:
      'Chất lưu hóa cao su ( dạng bột ) RUBBER ACCELERATOR (VULKALENT E/C), hàng mới 100%',
    originCountryCode: 'KR',
    originCountryName: 'R.KOREA',
  },
  {
    mst: 2700707969,
    buyerName: 'Công ty TNHH YG VINA',
    buyerAddress: 'Lô C2, KCN Gián Khẩu, huyện Gia Viễn, tỉnh Ninh Bình, ,',
    buyerMobile: '84303651989',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'M.BUWON ELECTRONIC CO.LTD',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 48192000,
    goodsDescription: 'Thùng carton AZZ 0469-500200. Mới 100%',
    originCountryCode: 'MM',
    originCountryName: 'MYANMAR',
  },
  {
    mst: 102655453,
    buyerName: 'Công ty TNHH Honda Trading Việt Nam',
    buyerAddress:
      'Tầng 8, toà nhà Mặt Trời Sông Hồng, 23 Phan Chu Trinh, P. Phan Chu Trinh, Q. Hoàn Kiếm, Hà Nội',
    buyerMobile: '0439334591',
    buyerRefCode: '',
    buyerRefName: '',
    sellerRefCode: '',
    sellerName: 'HONDA TRADING CORPORATION',
    postalCode: '',
    invoicePriceCondition: 'FOB',
    goodsCode: 87141090,
    goodsDescription:
      'Ống bằng thép dẫn dầu cho hệ thống phanh pipe comp b rr brake 43312-K77-V100 mới 100% phụ tùng xe máy honda',
    originCountryCode: 'TH',
    originCountryName: 'THAILND',
  },
]
