export const users = [
  {
    id: 1,
    username: 'admin',
    email: 'admin@gmail.com',
    role: 'admin',
    department: 'BOD',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
    password: '12345678',
  },
  {
    id: 2,
    username: 'leader',
    email: 'leader@gmail.com',
    role: 'leader',
    department: 'Ops',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
    password: '12345678',
  },
  {
    id: 3,
    username: 'staff',
    email: 'staff@gmail.com',
    role: 'staff',
    department: 'Ops',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
    password: '12345678',
  },
  {
    id: 4,
    username: 'director',
    email: 'director@gmail.com',
    role: 'director',
    department: 'Docs',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
    password: '12345678',
  },
  {
    id: 5,
    username: 'sale',
    email: 'sale@gmail.com',
    role: 'staff',
    department: 'Sale',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
    password: '12345678',
  },
]

export const permissions = [
  {
    key: 'staff',
    value: 1,
  },
  {
    key: 'leader',
    value: 2,
  },
  {
    key: 'director',
    value: 3,
  },
  {
    key: 'bod',
    value: 4,
  },
  {
    key: 'admin',
    value: 5,
  },
]
