export const headers = [
  { label: 'ID', key: 'id' },
  { label: 'Username', key: 'username' },
  { label: 'Email', key: 'email' },
  { label: 'Role', key: 'role' },
  { label: 'Department', key: 'department' },
  { label: 'Created at', key: 'createdAt' },
  { label: 'Updated at', key: 'updatedAt' },
  { label: 'Active', key: 'active' },
]
export const users = [
  {
    id: 1,
    username: 'admin',
    email: 'admin@gmail.com',
    role: 'admin',
    department: 'BOD',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
  },
  {
    id: 2,
    username: 'leader',
    email: 'leader@gmail.com',
    role: 'leader',
    department: 'Saler',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
  },
  {
    id: 3,
    username: 'user',
    email: 'user@gmail.com',
    role: 'user',
    department: 'Staff',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
  },
  {
    id: 4,
    username: 'director',
    email: 'director@gmail.com',
    role: 'director',
    department: 'Docs',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
  },
  {
    id: 5,
    username: 'accountant',
    email: 'docs@gmail.com',
    role: 'docs',
    department: 'Accountant',
    createdAt: '2021-01-01',
    updatedAt: '2021-01-01',
    active: true,
  },
]
